/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Enum.java to edit this template
 */
package dev.rayo.blogambiental.enumeraciones;

public enum Problematica {
    CAMBIO_CLIMATICO,
    CONTAMINACION_DEL_AIRE,
    CONTAMINACION_DEL_AGUA,
    DEFORESTACION,
    PERDIDA_DE_BIODIVERSIDAD,
    DESERTIFICACION,
    SOBREPESCA,
    DEGRADACION_DEL_SUELO,
    ESCASEZ_DE_AGUA,
    CONTAMINACION_QUIMICA,
    RESIDUOS_PLASTICOS,
    POLUCION_SONORA,
    IMPACTO_AMBIENTAL_DE_LA_MINERIA,
    URBANIZACION_EXTENSIVA,
    EMISIONES_DE_GASES_DE_EFECTO_INVERNADERO,
    ACIDIFICACION_DE_LOS_OCEANOS,
    DISMINUCION_DE_CAPAS_DE_HIELO,
    EVENTOS_CLIMATICOS_EXTREMOS,
    CONTAMINACION_LUMINICA,
    IMPACTO_AMBIENTAL_DEL_TURISMO,
    CONSTRUCCION_Y_CONSUMO_DE_RECURSOS_NO_SOSTENIBLE,
    IMPACTO_DE_LA_AGRICULTURA_INTENSIVA,
    PERTURBACION_DE_ECOLOGIAS_LOCALES
}

